name: Lint Codebase

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read
  packages: read
  statuses: write

jobs:
  lint:
    name: Lint Codebase
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          persist-credentials: false

      - uses: pnpm/action-setup@v6.0.3
        name: Install pnpm
        with:
          run_install: false

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v6.4.0
        with:
          node-version-file: .node-version
          cache: pnpm

      - name: Install Dependencies
        id: install
        run: pnpm install

      - name: Lint Codebase
        id: super-linter
        uses: super-linter/super-linter/slim@v8
        env:
          DEFAULT_BRANCH: main
          FILTER_REGEX_EXCLUDE: >-
            ^(dist/.*|pnpm-lock\.yaml|\.github/copilot-instructions\.md)$
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_GITHUB_ACTIONS_ZIZMOR: false
          LINTER_RULES_PATH: ${{ github.workspace }}
          VALIDATE_ALL_CODEBASE: true
          VALIDATE_JAVASCRIPT_ES: false
          VALIDATE_JAVASCRIPT_STANDARD: false
          VALIDATE_JSCPD: false
          VALIDATE_TYPESCRIPT_ES: false
          VALIDATE_JSON: false
          VALIDATE_TYPESCRIPT_STANDARD: false
          VALIDATE_CHECKOV: false
          VALIDATE_TYPESCRIPT_PRETTIER: false
          VALIDATE_PYTHON_BLACK: false
          VALIDATE_CSS_PRETTIER: false
          VALIDATE_SCSS_PRETTIER: false
          VALIDATE_SASS_PRETTIER: false
          VALIDATE_GRAPHQL_PRETTIER: false
          VALIDATE_HTML_PRETTIER: false
          VALIDATE_JAVASCRIPT_PRETTIER: false
          VALIDATE_JSON_PRETTIER: false
          VALIDATE_JSONC_PRETTIER: false
          VALIDATE_JSON5_PRETTIER: false
          VALIDATE_JSX_PRETTIER: false
          VALIDATE_VUE_PRETTIER: false
          VALIDATE_CSS_STYLELINT: false
          VALIDATE_SCSS_STYLELINT: false
          VALIDATE_SASS_STYLELINT: false
          VALIDATE_JSONC_ESLINT: false
          VALIDATE_JSON5_ESLINT: false
          VALIDATE_JSX_ESLINT: false
          VALIDATE_TSX_ESLINT: false
          VALIDATE_VUE_ESLINT: false
